#!/bin/bash -e

function reset_mt {
   sed -i 's/Mrr:.*/Mrr: 0.e20/' $1
   sed -i 's/Mtt:.*/Mtt: 0.e20/' $1
   sed -i 's/Mpp:.*/Mpp: 0.e20/' $1
   sed -i 's/Mrt:.*/Mrt: 0.e20/' $1
   sed -i 's/Mrp:.*/Mrp: 0.e20/' $1
   sed -i 's/Mtp:.*/Mtp: 0.e20/' $1
}

old="CMTSOLUTION"
new="CMTSOLUTION_Mrr"
cp $old $new
reset_mt  $new
sed -i 's/Mrr:.*/Mrr: 1.e20/' $new

old="CMTSOLUTION"
new="CMTSOLUTION_Mtt"
cp $old $new
reset_mt  $new
sed -i 's/Mtt:.*/Mtt: 1.e20/' $new

old="CMTSOLUTION"
new="CMTSOLUTION_Mpp"
cp $old $new
reset_mt  $new
sed -i 's/Mpp:.*/Mpp: 1.e20/' $new

old="CMTSOLUTION"
new="CMTSOLUTION_Mrt"
cp $old $new
reset_mt  $new
sed -i 's/Mrt:.*/Mrt: 1.e20/' $new

old="CMTSOLUTION"
new="CMTSOLUTION_Mrp"
cp $old $new
reset_mt  $new
sed -i 's/Mrp:.*/Mrp: 1.e20/' $new

old="CMTSOLUTION"
new="CMTSOLUTION_Mtp"
cp $old $new
reset_mt  $new
sed -i 's/Mtp:.*/Mtp: 1.e20/' $new

